# Exploratory Data Analysis on Austin Animal Center Intakes

## Table of Contents: 
 
   * [General Information](#general-information) 
   <br/><br/> 
   * [Aged Animals](#aged-animals) 
   <br/><br/> 
   * [Animals Returned](#animals-returned) 
   <br/><br/> 
   * [Location & Time](#location+time) 
   <br/><br/> 
       
    ethunasia 이유로 intake한 동물들이 ethunasia/died로 outcome 되었는 지
    intake에서 returned한 동물들이 outcome type이 무엇이었는 지

In [1]:
import pandas as pd

In [2]:
intakes = pd.read_csv('Cleaned_Intakes.csv')
outcomes = pd.read_csv('Cleaned_Outcomes.csv')

In [18]:
merged_outer = intakes.merge(outcomes,how='outer',on='Animal ID',suffixes=('_intakes','_outcomes'))
merged_outer.head()

,Animal ID,Name_intakes,DateTime_intakes,MonthYear_intakes,Found Location,Intake Type,Intake Condition,Animal Type_intakes,Sex upon Intake,Age upon Intake,...,DateTime_outcomes,MonthYear_outcomes,Date of Birth,Outcome Type,Outcome Subtype,Animal Type_outcomes,Sex upon Outcome,Age upon Outcome,Breed_outcomes,Color_outcomes
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,...,01/08/2019 03:11:00 PM,01/08/2019 03:11:00 PM,01/03/2017,Transfer,Partner,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,...,07/05/2015 03:13:00 PM,07/05/2015 03:13:00 PM,07/05/2007,Return to Owner,NaN,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,...,04/21/2016 05:17:00 PM,04/21/2016 05:17:00 PM,04/17/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,...,10/21/2013 11:39:00 AM,10/21/2013 11:39:00 AM,09/21/2013,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,...,07/02/2014 02:16:00 PM,07/02/2014 02:16:00 PM,06/29/2010,Return to Owner,NaN,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [6]:
merged_outer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 161674 entries, 0 to 161673
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Animal ID             161674 non-null  object
 1   Name_intakes          120975 non-null  object
 2   DateTime_intakes      160859 non-null  object
 3   MonthYear_intakes     160859 non-null  object
 4   Found Location        160859 non-null  object
 5   Intake Type           160859 non-null  object
 6   Intake Condition      160859 non-null  object
 7   Animal Type_intakes   160859 non-null  object
 8   Sex upon Intake       160858 non-null  object
 9   Age upon Intake       160859 non-null  object
 10  Breed_intakes         160859 non-null  object
 11  Color_intakes         160859 non-null  object
 12  Name_outcomes         121383 non-null  object
 13  DateTime_outcomes     161243 non-null  object
 14  MonthYear_outcomes    161243 non-null  object
 15  Date of Birth         161243 non-null  object
 16  Outcome Type          161214 non-null  object
 17  Outcome Subtype       63259 non-null   object
 18  Animal Type_outcomes  161243 non-null  object
 19  Sex upon Outcome      161242 non-null  object
 20  Age upon Outcome      161238 non-null  object
 21  Breed_outcomes        161243 non-null  object
 22  Color_outcomes        161243 non-null  object
dtypes: object(23)
memory usage: 29.6+ MB

In [22]:
merged_inner = intakes.merge(outcomes,how='inner',on='Animal ID')
merged_inner.head()

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type_x,Sex upon Intake,Age upon Intake,...,DateTime_y,MonthYear_y,Date of Birth,Outcome Type,Outcome Subtype,Animal Type_y,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,...,01/08/2019 03:11:00 PM,01/08/2019 03:11:00 PM,01/03/2017,Transfer,Partner,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,...,07/05/2015 03:13:00 PM,07/05/2015 03:13:00 PM,07/05/2007,Return to Owner,NaN,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,...,04/21/2016 05:17:00 PM,04/21/2016 05:17:00 PM,04/17/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,...,10/21/2013 11:39:00 AM,10/21/2013 11:39:00 AM,09/21/2013,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,...,07/02/2014 02:16:00 PM,07/02/2014 02:16:00 PM,06/29/2010,Return to Owner,NaN,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [23]:
merged_inner.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 160428 entries, 0 to 160427
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Animal ID         160428 non-null  object
 1   Name_x            120636 non-null  object
 2   DateTime_x        160428 non-null  object
 3   MonthYear_x       160428 non-null  object
 4   Found Location    160428 non-null  object
 5   Intake Type       160428 non-null  object
 6   Intake Condition  160428 non-null  object
 7   Animal Type_x     160428 non-null  object
 8   Sex upon Intake   160427 non-null  object
 9   Age upon Intake   160428 non-null  object
 10  Breed_x           160428 non-null  object
 11  Color_x           160428 non-null  object
 12  Name_y            120636 non-null  object
 13  DateTime_y        160428 non-null  object
 14  MonthYear_y       160428 non-null  object
 15  Date of Birth     160428 non-null  object
 16  Outcome Type      160399 non-null  object
 17  Outcome Subtype   62799 non-null   object
 18  Animal Type_y     160428 non-null  object
 19  Sex upon Outcome  160427 non-null  object
 20  Age upon Outcome  160423 non-null  object
 21  Breed_y           160428 non-null  object
 22  Color_y           160428 non-null  object
dtypes: object(23)
memory usage: 29.4+ MB

In [20]:
print("\n")
print("Total cases of intakes and outcomes "+ str(intakes.shape[0]+ outcomes.shape[0]))
print("\n")
print("The number of casee both intake and outcome happened " + str(merged_inner.shape[0]))
print("\n")
print("The number of intake cases without outcomes" + str(intakes.shape[0] - merged_inner.shape[0] ))
print("\n")
print("The number of outcome cases without intake" + str(outcomes.shape[0] - merged_inner.shape[0]))
print("\n")

Total cases of intakes and outcomes 248611


The number of casee both intake and outcome happened 160428


The number of intake cases without outcomes-36308


The number of outcome cases without intake-35937